import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PublicFooter, PublicHeader } from "@/app/components/public-chrome";
import { publicPageMetadata } from "@/lib/seo/metadata";

const content = {
  about: { title: "About ProperAP", intro: "A clearer, more connected way to search, present, and manage Jamaican property.", sections: [["Built for property professionals", "ProperAP gives brokerages and agents a shared approval-led platform for publishing reliable listings and serving clients with confidence."], ["Built for buyers and renters", "Visitors can search active properties, explore the professionals behind them, and choose the agent they want to contact."]] },
  careers: { title: "Careers", intro: "Help build the modern property platform for Jamaica and the Caribbean.", sections: [["Work with purpose", "We are building a practical service for real estate professionals and the people they serve."], ["Future opportunities", "We expect roles across customer operations, partner success, real estate data, design, and engineering as ProperAP grows."]] },
  feedback: { title: "Feedback", intro: "Tell us what would make ProperAP easier, clearer, or more useful.", sections: [["Your perspective matters", "We review feedback from property seekers, agents, brokerages, and partners as we improve the platform."], ["Share feedback", "For the current prototype, send your feedback to support@properap.com with the page name and a short description."]] },
  advertise: { title: "Advertise with ProperAP", intro: "Put your brokerage or professional profile in front of serious Jamaican property searchers.", sections: [["Recommended placements", "Featured brokerage and agent placements are managed by ProperAP to keep the marketplace useful and professional."], ["Coming soon", "Advertising packages will be introduced after the pilot, with transparent placement rules and clear labelling."]] },
  support: { title: "Support", intro: "Practical help for visitors, agents, brokerages, and ProperAP customers.", sections: [["For property seekers", "Use Search to filter active listings and choose the professional you wish to contact."], ["For professionals", "Sign in to manage listings, review approvals, and update your public professional website."], ["Need help?", "Email support@properap.com and include the page you were using plus a screenshot if possible."]] },
  privacy: { title: "Privacy", intro: "We handle personal information carefully and only for providing and improving ProperAP services.", sections: [["Information we use", "Account, inquiry, listing, and support details are used to operate the platform, deliver requested services, and protect the marketplace."], ["Your choices", "You may request access to or correction of your account information through ProperAP Support. This draft policy will be replaced with the formal launch policy before public release."]] },
  terms: { title: "Terms", intro: "Clear responsibilities for everyone using the ProperAP platform.", sections: [["Marketplace role", "ProperAP provides technology for publishing and discovering property. Brokerages remain responsible for approvals, listing accuracy, and professional conduct."], ["Membership, cancellation, and plan changes", "A monthly membership may be cancelled at any time and remains available until the end of its paid billing period. An annual commitment may be cancelled to stop automatic renewal, but the member remains responsible for the scheduled payments through the 12-month term. Plan changes take effect on the next billing date. ProperAP does not provide refunds or account credits for previously billed periods."], ["Former agent information and listing records", "When an agent cancels or leaves ProperAP, their public agent profile, personal website content, and related professional presentation data are deleted and no longer retained for an active service purpose. Limited account, security, billing, and compliance records may be retained where needed to operate the service or meet legal obligations. Past brokerage-owned listing records, including their approval and activity history, are retained as archived brokerage records; they are not kept publicly visible unless an active listing status permits it."], ["Pilot terms", "This prototype is for testing. Formal subscription, cancellation, privacy, retention, and platform terms will be reviewed by legal counsel and issued before commercial launch."]] },
} as const;
export type InformationSlug = keyof typeof content;
export function informationMetadata(slug: InformationSlug): Metadata { const page = content[slug]; return publicPageMetadata({ title: page.title, description: page.intro, path: `/${slug}` }); }
export function PublicInformationPage({ slug }: { slug: InformationSlug }) { const page = content[slug]; if (!page) notFound(); return <main className="public-information-page"><PublicHeader /><section className="public-information-hero"><span>ProperAP</span><h1>{page.title}</h1><p>{page.intro}</p></section><section className="public-information-content">{page.sections.map(([heading, body]) => <article key={heading}><h2>{heading}</h2><p>{body}</p></article>)}</section><PublicFooter /></main>; }
